---
- name: provisioning playbook for AMI instance
  hosts: all
  become: sudo
  become_user: ubuntu
  tags:
    - level-2
  roles:
    - { role: cis, when: ansible_distribution=="Ubuntu" and ansible_distribution_version=="14.04" }
