---
driver:
  name: ec2
  aws_ssh_key_id: rchawla-bootstrap
  security_group_ids: ["sg-00ea6e7e"]
  region: us-east-1
  availability_zone: b
  require_chef_omnibus: true
  instance_type: t1.micro
  associate_public_ip: true

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  # Use el7 epel repo instead of the default el6
  ansible_yum_repo: "https://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm"
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  # starting playbook is at: test/integration/default/default.yml

verifier:
  name: inspec

platforms:
  - name: aws-ubuntu-16.04
    driver_plugin: ec2
    driver:
      image_id: ami-4a83175c
    transport:
      ssh_key: ~/.ssh/rchawla-bootstrap
      username: ubuntu
suites:
  - name: default
