---
# # file: tasks/section-01.yml
# - name: remove old dirs from original setupcon
#   file: dest="{{ item }}" state="absent"
#   with_items:
#     - /var/log.old
#     - /var.old
#     - /home.old

- name: 1.1 Install Updates, Patches and Additional Security Software (Not Scored)
  apt: upgrade=dist update_cache=yes
  tags:
    - notscored
    - section1.1

- name: 1.1.1 Disable unused filesystems
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="{{item}}" insertafter=EOF state=present create=true
  with_items:
    - "install cramfs /bin/true"
    - "install freevxfs /bin/true"
    - "install jffs2 /bin/true"
    - "install hfs /bin/true"
    - "install hfsplus /bin/true"
    - "install squashfs /bin/true"
    - "install udf /bin/true"
    - "install vfat /bin/true"
  tags:
    - scored
    - section1.1.1

- name: 1.3.1 Ensure AIDE is installed (Scored)
  apt: name=aide update_cache=yes state=present
  notify: initialize aide
  tags:
    - scored
    - section1.3
    - section1.3.1

- name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
  lineinfile: dest="{{ item }}" line="0 5 * * * root /usr/bin/aide --check" insertafter=EOF state=present create=true
  with_items:
    - /var/spool/cron/crontabs/root
    - /etc/crontab
  tags:
    - section1.3
    - section1.3.2

  # cron:
  #   name: aide check
  #   minute: 0
  #   hour: 5
  #   user: root
  #   job: "/usr/bin/aide --check"
  #   cron_file: aide
  # tags:
  #   - scored
  #   - section1.3
  #   - section1.3.2
- name: 1.4.1 Ensure permissions on bootloader config are configured (Scored)
  command: chmod 400 /boot/grub/grub.cfg
  tags:
    - scored
    - section1.4
    - section1.4.1

- name: 1.5.1 Ensure core dumps are restricted /etc/security/limits.d/core-dump.conf (Scored)
  lineinfile: dest=/etc/security/limits.d/core-dump.conf line="* hard core 0" insertafter=EOF state=present create=true
  tags:
    - scored
    - section1.5
    - section1.5.1
- name: 1.5.1 Ensure core dumps are restricted sysctl (Scored)
  lineinfile: dest=/etc/sysctl.conf line="fs.suid_dumpable = 0" insertafter=EOF state=present create=true
  notify: limit core dumps realtime
  tags:
    - scored
    - section1.5
    - section1.5.1

- name: 1.5.1 Ensure core dumps are restricted sysctl (Scored)
  sysctl: name="fs.suid_dumpable" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  tags:
    - notscored
    - section1.5
    - section1.5.1

- name: 1.7.1 Command Line Warning Banners
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: "issue.net", dest: "/etc/issue.net" }
    - { src: "motd", dest: "/etc/motd" }
  tags:
    - scored
    - section1.7.1


# vim: set sw=2 ts=2:
