---
# file: tasks/section-03.yml

- include: section-03-level-1.yml
  tags:
    - level-1
    - section3-level-1

# - include: section-03-level-2.yml
#   tags:
#     - level-2
#     - section3-level-2

# vim: set sw=3 ts=3:
