---
# file: tasks/section-03-level-2.yml

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=0 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.all.send_redirects
  tags:
    - scored
    - section3.1
    - section3.1.2

- name: 3.2.1 Ensure source routed packets are not accepted (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=0 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
  tags:
    - scored
    - section3.2
    - section3.2.1

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=0 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
  tags:
    - scored
    - section3.1
    - section3.2.2

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=0 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
  tags:
    - scored
    - section3.1
    - section3.2.2

- name: 3.2.4 Ensure suspicious packets are logged (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=1 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  tags:
    - scored
    - section3.2
    - section3.2.4`

- name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=1 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.icmp_echo_ignore_broadcasts
  tags:
    - scored
    - section3.2
    - section3.2.4

- name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=1 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.icmp_ignore_bogus_error_responses
  tags:
    - scored
    - section3.2
    - section3.2.6

- name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored) sysctl.conf
  sysctl: name="{{item}}" value=1 ignoreerrors=yes value=1 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
  tags:
    - scored
    - section3.2
    - section3.2.7

- name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored) sysctl.conf
  sysctl: name="{{item}}" value=0 ignoreerrors=yes value=1 sysctl_set=yes reload=yes state=present
  with_items:
    - net.ipv4.tcp_syncookies
    - net.ipv4.conf.default.rp_filter
  tags:
    - scored
    - section3.2
    - section3.2.8

- name: 3.3 Configure IPv6
  debug: msg="*** If IPv6 is to be used, follow this section of the benchmark to configure IPv6, otherwise disable IPv6"
  tags:
    - section3.3

- name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Not Scored)
  sysctl: name="{{item}}" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  when: disable_ipv6 == "yes"
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  notify: flush ipv6 routing cache
  tags:
    - notscored
    - section3.3
    - section3.3.1

- name: 3.3.2 Ensure IPv6 redirects are not accepted (Not Scored)
  sysctl: name="{{item}}" value=0 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  when: disable_ipv6 == "yes"
  with_items:
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
  notify: flush ipv6 routing cache
  tags:
    - notscored
    - section3.3
    - section3.3.2

- name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
  sysctl: name="{{item}}" value=1 ignoreerrors=yes sysctl_set=yes reload=yes state=present
  when: disable_ipv6 == "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  notify: flush ipv6 routing cache
  tags:
    - notscored
    - section3.3
    - section3.3.3
# - name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
#   lineinfile: dest=/boot/grub/grub.cfg line="{{item}}" insertafter=EOF state=present create=true
#   lineinfile:
#     path: /etc/default/grub
#     regexp: '^GRUB_CMDLINE_LINUX=\"\"'
#     line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1"'
#   tags:
#     - notscored
#     - section3.3
#     - section3.3.3

- name: 3.4 TCP Wrappers
  debug: msg="***  TCP Wrappers add an additional layer of protection by defining which hosts are or are not allowed to connect to 'wrapped' network services"
  tags:
    - section3.4

- name: 3.4.1 Ensure TCP Wrappers is installed (Scored)
  apt: name=tcpd update_cache=yes  state=installed
  tags:
    - scored
    - section3.4
    - section3.4.1

- name: 3.4.2 Ensure /etc/hosts.allow is configured (Scored)
  file: path=/etc/hosts.allow state=touch
  tags:
    - notscored
    - section3.4
    - section3.4.2

- name: 3.4.3 Ensure /etc/hosts.deny is configured (Scored)
  file: path=/etc/hosts.deny state=touch
  tags:
    - notscored
    - section3.4
    - section3.4.3

- name: 3.4.4 Ensure permissions on /etc/hosts.allow are configured (Scored)
  file: path=/etc/hosts.allow owner=root group=root mode=0644
  tags:
    - scored
    - section3.4.4

- name: 3.4.5 Ensure permissions on /etc/hosts.deny are 644 (Scored)
  file: path=/etc/hosts.deny owner=root group=root mode=0644
  tags:
    - scored
    - section3.4
    - section3.4.5

- name: 3.5 Uncommon Network Protocols
  debug: msg="*** It is recommended to disable unused protocols in the kernel"
  tags:
    - section3.5

- name: 3.5.1 Ensure DCCP is disabled (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install dccp /bin/true" insertafter=EOF state=present create=true
  when: disable_dccp == "yes"
  tags:
    - section3.5
    - section3.5.1

- name: 3.5.2 Ensure SCTP is disabled (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install sctp /bin/true" insertafter=EOF state=present create=true
  when: disable_sctp == "yes"
  tags:
    - section3.5
    - section3.5.2

- name: 3.5.3 Ensure RDS is disabled (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install rds /bin/true" insertafter=EOF state=present
  when: disable_rds == "yes"
  tags:
    - notscored
    - section3.5
    - section3.5.3

- name: 3.5.4 Ensure TIPC is disabled (Not Scored)
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install tipc /bin/true" insertafter=EOF state=present
  when: disable_tipc == "yes"
  tags:
    - notscored
    - section3.5
    - section3.5.4

- name: 3.6 Firewall Configuration
  debug: msg="*** It is recommended to disable unused protocols in the kernel"
  tags:
    - section3.6

- name: 3.6.1 Ensure iptables is installed (Scored)
  apt: name="{{ item }}" update_cache=yes state=present
  with_items:
    - iptables
    - iptables-persistent
  tags:
    - section3.6
    - section3.6.1

- name: 3.6.3 Ensure loopback traffic is configured (Scored)
  command: "{{ item }}"
  with_items:
    - "iptables -A INPUT -i lo -j ACCEPT"
    - "iptables -A OUTPUT -o lo -j ACCEPT"
    - "iptables -A INPUT -s 127.0.0.0/8 -j DROP"
  notify: update iptables
  tags:
    - section3.6
    - section.3.6.3
