- name: Ensure auditd service is enabled (Scored)
  apt: name="auditd" update_cache=yes  state=installed
  tags:
    - scored
    - section4.1.2

- name: 4.1.1.1 Ensure audit log storage size is configured (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" line="max_log_file = {{ max_log_file }}" insertafter=EOF state=present create=yes
  tags:
    - notscored
    - section4.1.1.1

# we should have formal alterting mechanism once that's available - Ranbir
- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile: dest="/etc/audit/auditd.conf" line="{{ item }}" insertafter=EOF state=present create=yes
  with_items:
    - space_left_action = email
    - action_mail_acct = root
    - admin_space_left_action = halt
  tags:
    - scored
    - section4.1.1
    - section4.1.1.2

- name: 4.1.1.3 Ensure audit logs are not automatically deleted (Scored)
  lineinfile: dest="/etc/audit/auditd.conf" line="max_log_file_action = keep_logs" insertafter=EOF state=present create=yes
  tags:
    - scored
    - section4.1.1
    - section4.1.1.3

- name: 4.1.2 Ensure auditd service is enabled (Scored)
  command: systemctl enable auditd
  tags:
    - scored
    - section4.1.2

- name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  lineinfile: dest="/etc/default/grub" regexp="^GRUB_CMDLINE_LINUX=\"\"" line="GRUB_CMDLINE_LINUX=\"audit=1\""
  notify: update grub_path
  tags:
    - scored
    - section4.1
    - section4.1.3
- name: 4.1.4 Ensure events that modify date and time information are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change"
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b64 -S clock_settime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1
    - section4.1.4

- name: 4.1.5 Ensure events that modify user/group information are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /etc/group -p wa -k identity"
    - "-w /etc/passwd -p wa -k identity"
    - "-w /etc/gshadow -p wa -k identity"
    - "-w /etc/shadow -p wa -k identity"
    - "-w /etc/security/opasswd -p wa -k identity"
  notify: restart auditd
  tags:
    - scored
    - section4.1
    - section4.1.5

- name: 4.1.6 Ensure events that modify the system's network environment are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale"
    - "-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
    - "-w /etc/networks -p wa -k system-locale"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1
    - section4.1.6

- name: 4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{ item }}" insertafter=EOF state=present
  with_items:
    - -w /etc/selinux/ -p wa -k MAC-policy
    - -w /etc/apparmor/ -p wa -k MAC-policy
    - -w /etc/apparmor.d/ -p wa -k MAC-policy
  notify: restart auditd
  tags:
    - scored
    - section4.1.7

- name: 4.1.8 Ensure login and logout events are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/log/faillog -p wa -k logins"
    - "-w /var/log/lastlog -p wa -k logins"
    - "-w /var/log/tallylog -p wa -k logins"
  notify: restart auditd
  tags:
    - scored
    - section4.1.8

- name: 4.1.9 Ensure session initiation information is collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/run/utmp -p wa -k session"
    - "-w /var/log/wtmp -p wa -k session"
    - "-w /var/log/btmp -p wa -k session"
  notify: restart auditd
  tags:
    - scored
    - section4.1.9

- name: 4.1.10 Ensure discretionary access control permission modification events are collected (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1.10

- name: 4.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1.11

- name: 4.1.12 Collect Use of Privileged Commands (Scored)
  shell: /usr/bin/find {/usr/local/sbin,/usr/local/bin,/sbin,/bin,/usr/sbin,/usr/bin,/usr/lib} -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged" }'
  args:
    executable: /bin/bash
  register: privileged_programs
  tags:
    - scored
    - section8.1.12

- name: 4.1.12 Collect Use of Privileged Commands - DEBUG
  debug: var=privileged_programs.stdout_lines
  tags:
    - scored
    - section8.1.12

- name: 4.1.12 Collect Use of Privileged Commands (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items: "{{ privileged_programs.stdout_lines }}"
  when: privileged_programs is defined and privileged_programs.stdout_lines|length > 0
  notify: restart auditd
  tags:
    - scored
    - section8.1.12

- name: 4.1.13 Collect Successful File System Mounts (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
    - "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1.13

- name: 4.1.14 Collect File Deletion Events by User (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
    - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1.14

- name: 4.1.14 Collect File Deletion Events by User (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section4.1.14

- name: 4.1.15 Collect Changes to System Administration Scope (sudoers) (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /etc/sudoers -p wa -k scope"
    - "-w /etc/sudoers.d -p wa -k scope"
  notify: restart auditd
  tags:
    - scored
    - section4.1.15

- name: 4.1.16 Collect System Administrator Actions (sudolog) (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/log/sudo.log -p wa -k actions"
  notify: restart auditd
  tags:
    - scored
    - section8.1.16

- name: 4.1.17 Collect Kernel Module Loading and Unloading (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /sbin/insmod -p x -k modules"
    - "-w /sbin/rmmod -p x -k modules"
    - "-w /sbin/modprobe -p x -k modules"
    - "-a always,exit -F arch=b64 -S init_module -S delete_module -k modules"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section4.1.17

- name: 4.1.18 Make the Audit Configuration Immutable (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="-e 2" insertafter=EOF state=present
  notify: restart auditd
  tags:
    - scored
    - section4.1.18

- name: 4.2 Configure rsyslog
  debug: msg="*** rsyslog provides improvements over syslogd, such as connection-oriented (i.e. TCP) transmission of logs logging to database formats and encryption of log data during transmission."
  tags:
    - section8.2

- name: 4.2.1.1 Ensure rsyslog Service is enabled (Scored)
  apt: name=rsyslog update_cache=yes state=installed
  tags:
    - scored
    - section4.2
    - section4.2.1.1

- name: 4.2.1.2 Ensure logging is configured (Not Scored)
  service: name=rsyslog state=started enabled=yes
  tags:
    - scored
    - section8.2
    - section8.2.2

- name: 8.2.3 Configure /etc/rsyslog.conf (Not Scored)
  copy: src=rsyslog.d/CIS.conf dest=/etc/rsyslog.d/60-cis.conf owner=root group=root mode=0644
  notify: restart rsyslog
  tags:
    - notscored
    - section8.2
    - section8.2.3

- name: 4.2.1.3 Ensure rsyslog default file permissions configured (Scored)
  lineinfile: dest=/etc/rsyslog.conf regexp='^\$FileCreateMode' line="$FileCreateMode 0640" insertafter=EOF state=present
  notify: restart rsyslog
  tags:
    - scored
    - section8.2
    - section8.2.4

- name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host (Scored)
  debug: msg="*** will be done outside of base image creation"
  tags:
    - scored
    - section4.2
    - section4.2.1.4



# vim: set sw=2 ts=2:
